Repository openmsupply/openmsupply-client, pull requests merged in 2022-04, with the labels that each got.

#1138 #1130 Name details modal
  packages/common/src/hooks/useDialog/useDialog.tsx
  packages/common/src/intl/locales/en/common.json
  packages/common/src/ui/components/index.ts
  packages/common/src/ui/components/modals/BasicModal/BasicModal.tsx
  packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
  packages/common/src/ui/forms/Detail/NumericTextDisplay.tsx
  packages/common/src/ui/forms/Detail/index.ts
  packages/common/src/utils/formatters/formatters.ts
  packages/system/src/Item/DetailView/Tabs/General.tsx
  packages/system/src/Name/DetailModal/DetailModal.tsx
  packages/system/src/Name/DetailModal/index.ts
  packages/system/src/Name/ListView/ListView.tsx
  packages/system/src/Name/Service/Service.tsx
  packages/system/src/Name/api/api.ts
  packages/system/src/Name/api/hooks.ts
  packages/system/src/Name/api/operations.generated.ts
  packages/system/src/Name/api/operations.graphql
Labels: v1

#1144 Usability issues
  packages/common/src/intl/locales/en/common.json
  packages/common/src/intl/locales/en/distribution.json
  packages/common/src/intl/locales/en/replenishment.json
  packages/common/src/ui/layout/tables/DataTable.tsx
  packages/common/src/ui/layout/tables/columns/NameAndColorColumn.tsx
  packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  packages/invoices/src/InboundShipment/ListView/ListView.tsx
  packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
  packages/invoices/src/OutboundShipment/DetailView/modals/TaxEdit.tsx
  packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
Labels: v1

#1151 #1145 Date formatters
  packages/common/src/intl/date/IntlDate.ts
  packages/common/src/intl/date/index.ts
  packages/common/src/intl/index.ts
  packages/common/src/intl/utils/DateUtils.ts
  packages/common/src/intl/utils/index.ts
  packages/common/src/ui/components/domain/StatusCrumbs/StatusCrumbs.tsx
  packages/common/src/ui/layout/tables/columns/types.ts
  packages/common/src/ui/layout/tables/components/Cells/ExpiryDateCell/ExpiryDateCell.tsx
  packages/common/src/ui/layout/tables/components/index.tsx
  packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
  packages/common/src/utils/dates/DateUtils.ts
  packages/common/src/utils/dates/index.ts
  packages/common/src/utils/formatters/formatters.ts
  packages/common/src/utils/index.ts
  packages/invoices/src/InboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
  packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
  packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/ConsumptionHistory.tsx
  packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockEvolution.tsx
  packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  packages/requisitions/src/ResponseRequisition/DetailView/RelatedDocumentsSection.tsx
  packages/system/src/Name/DetailModal/DetailModal.tsx
Labels: Status: In progress

#1156 #1146 store changes on login
  packages/common/src/authentication/AuthContext.tsx
  packages/common/src/authentication/api/api.ts
  packages/common/src/authentication/api/hooks/index.ts
  packages/common/src/authentication/api/hooks/useAuthApi.ts
  packages/common/src/authentication/api/hooks/useStores.ts
  packages/common/src/authentication/api/hooks/useUserDetails.ts
  packages/common/src/authentication/api/operations.generated.ts
  packages/common/src/authentication/api/operations.graphql
  packages/common/src/intl/locales/en/app.json
  packages/common/src/localStorage/keys.ts
  packages/host/src/Site.tsx
  packages/host/src/components/AuthenticationAlert.tsx
  packages/host/src/components/Footer/StoreSelector.tsx
Labels: v1

#1168 Change column source
  packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Labels: Status: In progress, response

#1172 #577 speech bubble comment
  packages/common/src/ui/layout/tables/columns/CommentPopoverColumn/CommentPopoverColumn.tsx
  packages/common/src/ui/layout/tables/columns/CommentPopoverColumn/index.ts
  packages/common/src/ui/layout/tables/columns/index.ts
  packages/host/src/CommandK.tsx
  packages/host/src/Site.tsx
  packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Labels: Status: To do, request

#1174 A whole bunch of bits
  packages/common/src/intl/locales/en/common.json
  packages/common/src/intl/locales/en/distribution.json
  packages/common/src/intl/locales/en/replenishment.json
  packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  packages/invoices/src/InboundShipment/api/hooks.ts
  packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
  packages/invoices/src/OutboundShipment/DetailView/columns.ts
  packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundDelete.ts
  packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundAllocateSelectedLines.ts
  packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
  packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/ConsumptionHistory.tsx
  packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockDistribution.tsx
  packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
  packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx
  packages/requisitions/src/RequestRequisition/api/hooks.ts
Labels: Status: To do

#1180 Show name.isOnHold
  packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
  packages/common/src/ui/components/modals/ListSearch/ListSearch.tsx
  packages/invoices/src/InboundShipment/api/operations.generated.ts
  packages/invoices/src/InboundShipment/api/operations.graphql
  packages/invoices/src/OutboundShipment/api/operations.generated.ts
  packages/invoices/src/OutboundShipment/api/operations.graphql
  packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  packages/requisitions/src/RequestRequisition/api/operations.graphql
  packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  packages/requisitions/src/ResponseRequisition/api/operations.graphql
  packages/system/src/Name/Components/CustomerSearchInput/CustomerSearchInput.tsx
  packages/system/src/Name/Components/CustomerSearchModal/CustomerSearchModal.tsx
  packages/system/src/Name/Components/InternalSupplierSearchInput/InternalSupplierSearchInput.tsx
  packages/system/src/Name/Components/InternalSupplierSearchModal/InternalSupplierSearchModal.tsx
  packages/system/src/Name/Components/NameOptionRenderer/NameOptionRenderer.tsx
  packages/system/src/Name/Components/SupplierSearchInput/SupplierSearchInput.tsx
  packages/system/src/Name/Components/SupplierSearchModal/SupplierSearchModal.tsx
  packages/system/src/Name/api/operations.generated.ts
  packages/system/src/Name/api/operations.graphql
Labels: Blocked, system, Status: No API

#1175 Create multi option autocomplete list
  packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.stories.tsx
  packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
  packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMultiList.tsx
  packages/common/src/ui/components/inputs/Autocomplete/index.ts
  packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  packages/system/src/Item/Components/StockItemSelectModal/StockItemSelectModal.tsx
Labels: refactor

#1178 Export lists to csv
  package.json
  packages/common/src/intl/locales/en/common.json
  packages/common/src/utils/files/FileUtils.ts
  packages/common/src/utils/files/index.ts
  packages/common/src/utils/formatters/formatters.ts
  packages/common/src/utils/index.ts
  packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx
  packages/inventory/src/Stocktake/ListView/ListView.tsx
  packages/inventory/src/Stocktake/api/api.ts
  packages/inventory/src/Stocktake/api/hooks.ts
  packages/inventory/src/utils.ts
  packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
  packages/invoices/src/InboundShipment/ListView/ListView.tsx
  packages/invoices/src/InboundShipment/api/api.ts
  packages/invoices/src/InboundShipment/api/hooks.ts
  packages/invoices/src/OutboundShipment/ListView/AppBarButtons.tsx
  packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  packages/invoices/src/OutboundShipment/api/api.ts
  packages/invoices/src/OutboundShipment/api/hooks/document/index.ts
  packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundsAll.ts
  packages/invoices/src/OutboundShipment/api/hooks/index.ts
  packages/invoices/src/OutboundShipment/api/hooks/utils/useOutboundApi.ts
  packages/invoices/src/utils.ts
  packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  packages/requisitions/src/RequestRequisition/api/api.ts
  packages/requisitions/src/RequestRequisition/api/hooks.ts
  packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
  packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  packages/requisitions/src/ResponseRequisition/api/api.ts
  packages/requisitions/src/ResponseRequisition/api/hooks.ts
  packages/requisitions/src/utils.ts
  packages/system/src/Location/ListView/AppBarButtons.tsx
  packages/system/src/Location/ListView/ListView.tsx
  packages/system/src/Location/api/hooks.ts
  packages/system/src/MasterList/ListView/AppBarButtons.tsx
  packages/system/src/MasterList/ListView/ListView.tsx
  packages/system/src/MasterList/api/api.ts
  packages/system/src/MasterList/api/hooks.ts
  packages/system/src/utils.ts
  yarn.lock
Labels: outbound

#1182 Manually created inbound status values
  packages/common/src/api/hooks/useFieldsSelector/useFieldsSelector.ts
  packages/common/src/authentication/AuthContext.tsx
  packages/common/src/authentication/api/hooks/useUserDetails.ts
  packages/common/src/intl/locales/en/replenishment.json
  packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
  packages/common/src/ui/components/panels/InfoPanel.stories.tsx
  packages/common/src/ui/components/panels/InfoPanel.tsx
  packages/common/src/ui/components/panels/index.ts
  packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
  packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  packages/invoices/src/InboundShipment/api/hooks.ts
  packages/invoices/src/InboundShipment/api/operations.generated.ts
  packages/invoices/src/InboundShipment/api/operations.graphql
  packages/invoices/src/utils.ts
Labels: inbound

#1190 1189 fix tests
  jest.config.js
  package.json
  packages/common/src/hooks/useAppBarRect/useAppBarRect.test.tsx
  packages/common/src/hooks/useBoundingClientRect/useBoundingClientRect.test.tsx
  packages/common/src/hooks/useDebounce/useDebounceCallback.test.tsx
  packages/common/src/hooks/useDebounce/useDebouncedValue.test.tsx
  packages/common/src/hooks/useDetailPanel/useDetailPanel.test.tsx
  packages/common/src/hooks/useEditModal/useEditModal.test.tsx
  packages/common/src/hooks/useEffectAfterMounting/useEffectAfterMounting.test.ts
  packages/common/src/hooks/useFilterBy/useFilterBy.test.tsx
  packages/common/src/hooks/useIsMountedRef/useIsMountedRef.test.tsx
  packages/common/src/hooks/useIsScreen/useIsExtraLargeScreen.test.ts
  packages/common/src/hooks/useIsScreen/useIsLargeScreen.test.ts
  packages/common/src/hooks/useIsScreen/useIsMediumScreen.test.ts
  packages/common/src/hooks/useIsScreen/useIsSmallScreen.test.ts
  packages/common/src/hooks/usePagination/usePagination.test.ts
  packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx
  packages/common/src/hooks/useSortBy/useSortBy.test.ts
  packages/common/src/hooks/useWindowDimensions/useWindowDimensions.test.tsx
  packages/common/src/intl/context/IntlContext.tsx
  packages/common/src/intl/locales/en/common.json
  packages/common/src/intl/locales/en/inventory.json
  packages/common/src/ui/components/menus/ColorMenu/ColorMenu.test.tsx
  packages/common/src/ui/components/menus/DropdownMenu/DropdownMenu.test.tsx
  packages/common/src/ui/components/menus/DropdownMenu/DropdownMenu.tsx
  packages/common/src/ui/components/navigation/Tabs/Tabs.test.tsx
  packages/common/src/ui/components/navigation/Tabs/useTabs.test.ts
  packages/common/src/ui/components/popover/BasePopover/BasePopover.test.tsx
  packages/common/src/ui/components/popover/BasePopover/usePopover.test.tsx
  packages/common/src/ui/components/portals/AppBarButtons/AppBarButtons.test.tsx
  packages/common/src/ui/components/portals/AppBarContent/AppBarContent.test.tsx
  packages/common/src/ui/components/portals/AppFooter/AppFooter.test.tsx
  packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.test.tsx
  packages/common/src/ui/layout/tables/components/Header/Header.test.tsx
  packages/common/src/ui/layout/tables/context/TableContext.test.tsx
  packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.test.tsx
  packages/common/src/utils/testing/testing.tsx
  packages/host/src/components/AppDrawer/AppDrawer.test.tsx
  packages/inventory/src/Stocktake/ListView/Toolbar.tsx
  packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useNextItem.test.tsx
  yarn.lock
Labels: Chore, bump:patch

#1191 commit test
  .github/workflows/bumpr.yaml
Labels: bump:patch
